### ISSUE TITLE
Wildcard glob-patterns doesn't seem to work as expected

### ISSUE THREAD

**Issue by marioleed** [launchdarkly/ld-find-code-refs#146]
I'm trying to [generate aliases with filepattern as recommended in the docs](https://github.com/launchdarkly/ld-find-code-refs/blob/master/docs/ALIASES.md#search-files-for-a-specific-pattern) and it seems as I can only manage to generate aliases when the paths are explicit (i.e. without any wildcards or glob-patterns).

The docs example:

```yaml
aliases:
  - type: filepattern
    paths:
      - '*[!_test].go'
    patterns: 
      - '(\w+) = "FLAG_KEY"'
```

My try at it:

Running on macOS Big Sur 11.3.1, Z-shell
ld-find-code-refs version 2.2.2

`some-repo-name/.launchdarkly/coderefs.yaml`:
```yaml
projKey: some-project
repoName: some-repo-name
aliases:
  - type: filepattern
    paths:
      # None of the uncommented lines work, neither separate or together
      - '*.cs'
      - '*/FeatureFlags/*.cs'
      - 'Some.Project.Domain/FeatureFlags/*.cs'
      - 'Some.Project.Domain/FeatureFlags/US*.cs'
      - 'Some.Project.Domain/FeatureFlags/US+([0-9])_*.cs'
      # All below works if I uncomment - both separate and together - also here you can see the directory tree
      # - 'Some.Project.Domain/FeatureFlags/US12345_UseMyExampleFlag.cs'
      # - 'Some.Project.Domain/FeatureFlags/US54321_SomeOtherFlag.cs'
      # - '/Some.Project.Domain/FeatureFlags/US33333_ShowImprovedButton.cs'
    patterns:
      - 'public class \b(?P<FLAG_ALIAS>\w+)\b[\s\n]*:[\s\n]*FeatureFlag<\w+>[\s\n]*\s*{[\s\n]*\s*public override string Keyname[\s\n]*=>[\s\n]*"FLAG_KEY"'
```

`Some.Project.Domain/FeatureFlags/US12345_UseMyExampleFlag.cs`: (all the other have the same pattern)

```csharp
using Some.Project.Common.FeatureFlags;

// ReSharper disable InconsistentNaming

namespace Some.Project.Domain.FeatureFlags
{
    public class US12345_UseMyExampleFlag : FeatureFlag<bool>
    {
        public override string Keyname => "some-project-12345-63cc-3e7b-c406-90fae8899f42";
    }
}
```

Running from command line (provided `LD_ACCESS_TOKEN` is already set):

```bash
ld-find-code-refs -d some-repo-name --debug --dryRun 
```
Same results for
```bash
ld-find-code-refs -d /Users/myuser/Source/some-repo-name --debug --dryRun 
```

Results for **explicit paths**:
> INFO: 2021/05/12 10:04:38 coderefs.go:32: absolute directory path: /Users/myuser/Source/some-repo-name
DEBUG: 2021/05/12 10:04:38 git.go:68: identified branch name: master
INFO: 2021/05/12 10:04:38 git.go:48: git branch: master
DEBUG: 2021/05/12 10:04:38 git.go:83: identified head sha: 123456baf7b14f29e9e568592e9006b10e502e20
                     FLAG                    | # REFERENCES  
+--------------------------------------------+--------------+
  some-project-12345-63cc-3e7b-c406-90fae8899f42 |            3 
  some-project-12345-63cc-3e7b-c406-90fae8899f42 |            2  
  some-project-12345-a457-402e-ba83-30a6be3e4c7e |            4  
  Other flags                                |            0  
INFO: 2021/05/12 10:04:41 coderefs.go:129: dry run found 9 code references across 93 flags and 6 files

Results for **glob patterns**:
> INFO: 2021/05/12 10:04:38 coderefs.go:32: absolute directory path: /Users/myuser/Source/some-repo-name
DEBUG: 2021/05/12 10:04:38 git.go:68: identified branch name: master
INFO: 2021/05/12 10:04:38 git.go:48: git branch: master
DEBUG: 2021/05/12 10:04:38 git.go:83: identified head sha: 123456baf7b14f29e9e568592e9006b10e502e20
                     FLAG                    | # REFERENCES  
+--------------------------------------------+--------------+
  some-project-12345-63cc-3e7b-c406-90fae8899f42 |            1 
  some-project-12345-63cc-3e7b-c406-90fae8899f42 |            1  
  some-project-12345-a457-402e-ba83-30a6be3e4c7e |            1  
  Other flags                                |            0  
INFO: 2021/05/12 10:04:41 coderefs.go:129: dry run found 3 code references across 93 flags and 3 files

When I run this I do get matches, so I'm not sure really what happens in alias.go:

```go
package main

import (
	"fmt"
	"path/filepath"
)

func main() {
	dir := "/Users/myuser/Source/some-repo-name"
	glob := "*/FeatureFlags/*.cs"

	absGlob := filepath.Join(dir, glob)
	fmt.Println("Absolute glob: " + absGlob)

	matches, err := filepath.Glob(absGlob)

	if err != nil {
		fmt.Println("filepattern could not process path glob:" + absGlob)
	}

	for i, s := range matches {
		fmt.Println(i, s)
	}
}
```

Results:
> Absolute glob: /Users/myuser/Source/some-repo-name/*/FeatureFlags/*.cs
0 /Users/myuser/Source/some-repo-name/Some.Project.Domain/FeatureFlags/US12345_UseMyExampleFlag.cs
1 /Users/myuser/Source/some-repo-name/Some.Project.Domain/FeatureFlags/US54321_SomeOtherFlag.cs
2 /Users/myuser/Source/some-repo-name/Some.Project.Domain/FeatureFlags/US33333_ShowImprovedButton.cs

What am I missing? I get the same results for a react project with .ts files.
