### ISSUE TITLE
Tool gets stuck when defining glob filepattern on big repo

### ISSUE THREAD

**Issue by kostyay** [launchdarkly/ld-find-code-refs#377]
Hey
This is my config:
```yaml
aliases:
  - type: kebabcase
  - type: filepattern
    paths:
      - '**/manifest.yaml'
    patterns:
      - 'featureFlag: FLAG_KEY'
      - 'feature_flag: FLAG_KEY'
```

Running the tool like this:
```
ld-find-code-refs -t KEY -d ./ -p default -r REPO --debug -b master -T github -B master --dryRun -C 0 -l 1
```

Get the following output and the tool gets stuck:
```
INFO: 2023/08/10 20:15:58 coderefs.go:27: absolute directory path: XXXX
INFO: 2023/08/10 20:15:58 git.go:48: git branch: master
DEBUG: 2023/08/10 20:15:58 git.go:169: identified head sha: XXXXX
```

Could it be that I got rate limited because I was running it a bunch of times?
There are 317 files matching that pattern in the repo.

Sometimes it works then I get this output:
```dry run found 1113 code references across 720 flags and 844 files```

However its still not finding everything I'd expect to be found.
Is there a more verbose debugging mode?
