### ISSUE TITLE
Not finding random refs

### ISSUE THREAD

**Issue by boonew2** [launchdarkly/ld-find-code-refs#390]
I've been experimenting with this utility and from my testing so far it seems to be missing seemingly random references.

`.launchdarkly/coderefs.yaml`
```
aliases:
  - type: pascalcase
```

The codebase is largely C# and there is a file that has all of the flags accounted for as named constants converted to pascal case.  I'm slightly modifying the names here, but the cs file has this in it:
```
public static ToggleKey Qa_Updates => new ToggleKey( nameof( Qa_Updates ) );
public static ToggleKey Authz => new ToggleKey( nameof( Authz ) );
```
and the flags in LD are called `qa_updates` and `authz`. The reference to authz is found correctly and reported, but qa_updates is not. There are other references across the codebase to `Qa_Updates ` and `Authz`, but i'm focusing on this file specifically because it seemed like the most apples to apples comparison of mixed results.  

Just to try and make sure the `pascalcase` alias was doing what i expected i re-implemented it with with a command alias:
```
 aliases:
  #- type: pascalcase
  - type: command
    command: python ./.launchdarkly/aliases.py
    timeout: 5
```
```
#! /usr/bin/env python
import sys,json
for flag_key in sys.stdin:
    flag_key = flag_key.strip()
    alias = '_'.join([word.capitalize() for word in flag_key.split('_')])
    aliases = json.dumps([alias])
    print(aliases)
    break
```
and got the exact same results with respect to those flags.
Output from running the tool:
```
INFO: 2023/09/27 15:57:28 coderefs.go:27: absolute directory path: REDACTED
INFO: 2023/09/27 15:57:28 git.go:48: git branch: REDACTED
INFO: 2023/09/27 15:57:47 coderefs.go:148: sending 1090 code references across 909 flags and 331 files to LaunchDarkly for project(s): [ default]
INFO: 2023/09/27 15:57:48 coderefs.go:182: checking if 869 flags without references were removed in the last 10 commits for project: default
INFO: 2023/09/27 15:57:48 coderefs.go:187: found 0 removed flags
INFO: 2023/09/27 15:57:48 coderefs.go:199: attempting to prune old code reference data from LaunchDarkly
WARNING: 2023/09/27 15:57:48 coderefs.go:202: unable to retrieve branch list from remote, skipping code reference pruning: authentication required
```

**Comment by jazanne** [comment]
@boonew2 thanks for including all of this info

our alias tool uses https://github.com/iancoleman/strcase under the hood, and would convert a flag like `qa_updates` to `QaUpdates` - removing the underscore that you have in your code.

I'm not sure why you're not seeing the aliases from the custom command - i added a test cases for both of the situations you describe and the aliases appear to be generated correctly 

https://github.com/launchdarkly/ld-find-code-refs/pull/391/files


Can you share with me how you're running the tool?

**Comment by boonew2** [comment]
Thanks for the quick response! I haven't plumbed it into our ci process yet since I'm just testing right now so i'm just calling it ad hoc from my computer.
The full coderefs file looks like this:
```
---
projKey: default
contextLines: 2
repoName: REDACTED
repoUrl: https://github.com/REDACTED/REDACTED
repoType: github

ignoreServiceErrors: true

aliases:
  #- type: pascalcase
  - type: command
    command: python ./.launchdarkly/aliases.py
    timeout: 5
```
and from the powershell i just have:
```
& 'C:\temp\ld-find-code-refs.exe' --accessToken "REDACTED" --dir C:\path\to\repo
```
