### ISSUE TITLE
Issue: sending 0 code references across 313 flags and 0 files to LaunchDarkly for project(s):

### ISSUE THREAD

**Issue by jmgawecki** [launchdarkly/ld-find-code-refs#393]
Scan succeeds but finds no references.

Our yaml file:
```yaml
name: Find LaunchDarkly flag code references
on:
  push:
    branches:
      - develop
      - story/IT-736
# cancel in-flight workflow run if another push was triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  launchDarklyCodeReferences:
    name: LaunchDarkly Code References
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 11 # This value must be set if the lookback configuration option is not disabled for find-code-references. Read more: https://github.com/launchdarkly/ld-find-code-refs#searching-for-unused-flags-extinctions
      - name: LaunchDarkly Code References
        uses: launchdarkly/find-code-references@v2.10.0
        with:
          accessToken: ${{ secrets.LD_ACCESS_TOKEN }}
          projKey: default
          default_branch: story/IT-736
```

Result of the scan:

> INFO: 2023/10/02 15:06:01 coderefs.go:148: sending 0 code references across 313 flags and 0 files to LaunchDarkly for project(s): [ default]

The very same configuration on our Android project works just fine, finds reference and sends them to LD UI. 
I've checked the gitignore file as I've seen that entry .* may cause some issues but it's not the case for us.

Thanks for help
